### ISSUE TITLE
3.1: npm and yarn scripts

### ISSUE THREAD

**Issue by frankiebarrios** [frankiebarrios/frankie-barrios-ux-aop#12]
## Main Goals
1. Serve static HTML files in a local server for development purposes.
2. Write an npm script to run the serve operation.
### When Accomplished
- [x] `package.json` file includes `scripts` object with `start` property that runs a server on `http://localhost:1820`
- [x] `yarn start` runs the server
- [x] `http://localhost:1820` loads an HTML page in a browser
  - This may require you to rename an HTML file to `index.html`
- [x] Description of `start` script exists in `package.json`
## Research
1. [Introduction to NPM Scripts](https://medium.freecodecamp.org/introduction-to-npm-scripts-1dbb2ae01633)
  - The scripts you write will be pretty basic. This article goes into details on how to replace build operations with scripts--none of that is necessary right now.
1. [Yarn docs: `yarn run`](https://yarnpkg.com/en/docs/cli/run)
## Notes
- Eventually `webpack-dev-server` will run the server automatically, but it will be useful to have a method of serving your HTML content without relying on Webpack.
- There are many npm packages that can run servers. `http-server` and `serve` have simple APIs and are easy to implement. If you're looking for a challenge, you can write one from scratch using Node, or run a simple `express` server.
- `yarn run start` and `yarn start` do the same thing.
- In the past we have used [Gulp](https://gulpjs.com/) (a 'taskrunner') to do the work that npm scripts does here. Gulp does a lot of things that npm scripts are used for (run project-level command line operations like code linting) as well as steps we use Webpack for (bundling dependencies and building the project). Webpack is better for dependency management and bundling than Gulp, so it benefits projects like this in many ways that Gulp doesn't.

## Resources
- [`http-server`](https://www.npmjs.com/package/http-server)
- [`serve`](https://www.npmjs.com/package/serve)
- [Overview of HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview)

**Comment by kddrake** [comment]
closed by #15
