### ISSUE TITLE
2.1: Creating HTML Pages

### ISSUE THREAD

**Issue by frankiebarrios** [frankiebarrios/frankie-barrios-ux-aop#5]
## Main Goals
1. Create static HTML pages to display user information
2. Create accessible forms to input user information
3. Create and implement a persistent navigation pattern

### When Accomplished
1. The User Profile HTML page
    - [x] has one user profile displaying information following the [user data model](https://github.com/Banno/ux-intern-onboarding/blob/master/resources/specs/localStorage-api-spec.md#the-user-model)
2. The User List HTML page
    - [x] shows several condensed user profiles in contrast to the complete profile on the User Profile page
3. The Create User HTML page
    - [x] contains a form to create a new user with a field for each public property in the [user data model](https://github.com/Banno/ux-intern-onboarding/blob/master/resources/specs/localStorage-api-spec.md#the-user-model)
    - [x] form uses [accessibility markup](http://www.washington.edu/accessibility/checklist/forms/) such as `id` attributes and `<label>` tags to give the form basic accessibility
      - Both the form and submit button do not need to be operational
4. The Edit User HTML page
    - [x] contains a form to edit an existing user
        - Should be identical to the Create User form
    - [x] form uses [accessibility markup](http://www.washington.edu/accessibility/checklist/forms/) such as `id` attributes and `<label>` tags to give the form basic accessibility
        - Both the form and submit button do not need to be operational
5. All HTML pages
  - [x] have an identical and functioning navigation

## Research

- From [Clean Code](https://drive.google.com/a/banno.com/file/d/0Bwz8B78G4U8BLVltUDV4R0VPdTg/view):
  - Chapter 1: Clean Code
  - Chapter 4: Comments
- [Dive into HTML5](http://diveintohtml5.info/semantics.html)
- [HTML & CSS is Hard (But it doesn't have to be)](https://internetingishard.com/html-and-css/)
- From Chad Killingsworth's Tech Talks:
  - [HTML5 as a Semantic Language](https://youtu.be/OJsFiCQ-d1I)
  - [CSS - Quirks of the Box Model](https://youtu.be/sQY7ZLXCZlk)

## Resources
  - [MDN web docs: `<a>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)

## Notes
1. For now, the user profile and user list pages should be populated with dummy data. Eventually this data will be retrieved from `localStorage`.
2. All pages will eventually be tied to the same data, so dummy data should follow [the user data model](https://github.com/Banno/ux-intern-onboarding/blob/master/resources/specs/localStorage-api-spec.md#the-user-model).

**Comment by kddrake** [comment]
closed by #8
