### ISSUE TITLE
2.2: Basic Styling

### ISSUE THREAD

**Issue by frankiebarrios** [frankiebarrios/frankie-barrios-ux-aop#6]
## Main Goals
1. Gain a basic understanding of CSS
2. Apply styles to the project to make things visually appealing
3. Use CSS to change the layout of the project in a meaningful, UX-improving way

### When Accomplished
1. Your CSS
    - [ ] is housed in a single CSS file
    - [ ] is utilized on every page
    - [ ] uses at least one class selector to standardize styles for a type of HTML object.
    - [ ] defines a standard layout for each page to follow.

## Research
- [CSS - Quirks of the Box Model](https://youtu.be/sQY7ZLXCZlk)

## Notes
- You can experiment with newer technologies like [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout), [Flexbox](https://developer.mozilla.org/en-US/docs/Glossary/Flexbox), or [animations](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations), but nothing too intense is required.  The purpose here is to demonstrate a basic understanding of CSS.

**Comment by kddrake** [comment]
closed by #10
