### ISSUE TITLE
2.3: Basic JavaScript: Minimizing/Expanding Functionality

### ISSUE THREAD

**Issue by frankiebarrios** [frankiebarrios/frankie-barrios-ux-aop#9]
# 2.3: Basic JavaScript: Minimizing/Expanding Functionality
With Webpack and Polymer set up, we're going to go back to your HTML files for a bit and add some basic JavaScript.
## Main Goal
Add expanding and minimizing functionality to the user profile
### When Accomplished
- [x] Clicking a button will expand the user profile
  - [x] The button is styled in a way that says "hey, I'll expand the profile if you click me"
- [x] Clicking a button will minimize the user profile 
  - [x] The button is styled in a way that says "hey, le'me make this profile a little smaller"
## Side Goal
Have expanding and minimizing functionality run by the same button
### When Accomplished
- [x] If minimized, clicking the button will expand the user profile
- [x] If expanded, clicking the button will minimize the user profile
## Research
1. From [Clean Code](https://drive.google.com/a/banno.com/file/d/0Bwz8B78G4U8BLVltUDV4R0VPdTg/view):
    - Chapter 2: Meaningful Names
    - Chapter 3: Functions
    - Chapter 5: Formatting
2. From _You Don't Know JS_:
    - [Up & Going (Chapter 2): Intro to JS](https://github.com/getify/You-Dont-Know-JS/blob/master/up%20&%20going/ch2.md)
3. From Chad Killingsworth's Tech Talks:
    - [Intro to JavaScript Types](https://www.youtube.com/watch?v=VLeD9fS3y1U&index=3&list=PLCoQ3TMLaKeRUoi_7iMhxtclAJjX25Apg)
    - [JavaScript Scopes](https://www.youtube.com/watch?v=NA3LqD_gSrk&index=6&list=PLCoQ3TMLaKeRUoi_7iMhxtclAJjX25Apg)
## Resources
- [Document Object Model (DOM): MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model)
- [EventTarget.addEventListener(): MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)
- [_Eloquent JavaScript_](https://eloquentjavascript.net/)

**Comment by kddrake** [comment]
closed by #11
